name: Publish GitHub Pages

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v1.1, etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push build artifacts
      pages: write    # To deploy to GitHub Pages
      id-token: write # Required for actions/deploy-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for actions/upload-pages-artifact

      - name: Setup Pages
        uses: actions/configure-pages@v4

      

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Path to your build output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4